# Generated by Django 5.1.2 on 2024-10-22 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('type_of_driver', models.CharField(max_length=100)),
                ('pondo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('release_year', models.DateField()),
                ('plate_number', models.CharField(max_length=10, unique=True)),
                ('service_status', models.CharField(max_length=20)),
                ('day_of_coding', models.CharField(max_length=10)),
                ('taxi_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('boundary_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='driverMonitoring.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('contact_number', models.CharField(blank=True, max_length=13, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('office staff', 'Office Staff')], default='driver', max_length=20)),
                ('image', models.URLField(blank=True, default='')),
                ('date_started', models.DateField(auto_now_add=True)),
                ('birthday', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driverMonitoring.employee'),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('contribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('sss', models.IntegerField()),
                ('pag_ibig', models.IntegerField()),
                ('philhealth', models.IntegerField()),
                ('total', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='driverMonitoring.employee')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='taxi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='driverMonitoring.taxi'),
        ),
    ]
