# Generated by Django 5.1.3 on 2024-11-28 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('release_year', models.DateField()),
                ('plate_number', models.CharField(max_length=10, unique=True)),
                ('condition', models.CharField(choices=[('parked', 'Parked'), ('repairing', 'Repairing'), ('coding', 'Coding'), ('deployed', 'Deployed')], default='parked', max_length=20)),
                ('day_of_coding', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='monday', max_length=10)),
                ('taxi_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_type', models.CharField(choices=[('daily', 'Daily'), ('alternate', 'Alternate')], default='daily', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('contact_number', models.CharField(blank=True, max_length=13, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('office staff', 'Office Staff')], default='driver', max_length=20)),
                ('image', models.URLField(blank=True, default='')),
                ('date_started', models.DateField(auto_now_add=True)),
                ('birthday', models.DateField(null=True)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('contribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('sss', models.IntegerField()),
                ('pag_ibig', models.IntegerField()),
                ('philhealth', models.IntegerField()),
                ('total', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='driverMonitoring.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeStaff',
            fields=[
                ('office_staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_role', models.CharField(choices=[('admin', 'Admin'), ('dispatcher', 'Dispatcher'), ('mekaniko', 'Mekaniko'), ('liaison', 'Liaison')])),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driverMonitoring.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('type_of_driver', models.CharField(choices=[('daily', 'Daily'), ('alternate', 'Alternate')], max_length=100)),
                ('pondo', models.IntegerField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driverMonitoring.employee')),
                ('taxi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drivers', to='driverMonitoring.taxi')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('dispatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('park_or_dispatch', models.CharField(choices=[('park', 'Park'), ('dispatch', 'Dispatch')])),
                ('status', models.CharField(choices=[('good', 'Good'), ('need maintenance', 'Needmaintenance')], default='good')),
                ('boundary', models.IntegerField()),
                ('gas', models.IntegerField()),
                ('date_and_time', models.DateTimeField()),
                ('image', models.URLField(default='', null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='driverMonitoring.driver')),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='driverMonitoring.taxi')),
            ],
        ),
    ]
