# Generated by Django 5.1.3 on 2024-11-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='target_boundary',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='park_or_dispatch',
            field=models.CharField(choices=[('park', 'Park'), ('dispatch', 'Dispatch')], max_length=20),
        ),
    ]
