# Generated by Django 5.1.3 on 2024-11-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0002_taxi_target_boundary_alter_dispatch_park_or_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='is_short',
            field=models.BooleanField(default=False),
        ),
    ]
