# Generated by Django 5.1.2 on 2024-10-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0003_officestaff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officestaff',
            old_name='office_staff',
            new_name='office_staff_id',
        ),
    ]
