# Generated by Django 5.1.3 on 2024-11-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0003_dispatch_is_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='gas_deficit',
            field=models.IntegerField(default=0),
        ),
    ]
