# Generated by Django 5.1.2 on 2024-10-26 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0004_rename_office_staff_officestaff_office_staff_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='taxi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drivers', to='driverMonitoring.taxi'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='type_of_driver',
            field=models.CharField(choices=[('daily', 'Daily'), ('alternate', 'Alternate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='plate_number',
            field=models.CharField(max_length=10),
        ),
    ]
