# Generated by Django 5.1.3 on 2024-11-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0004_dispatch_gas_deficit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='gas',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='gas_deficit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
