# Generated by Django 5.1.3 on 2024-11-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0006_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='travel_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('alternate', 'Alternate')], default='daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='pondo',
            field=models.IntegerField(default=0),
        ),
    ]
