# Generated by Django 5.1.3 on 2024-11-30 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0007_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='date_and_time',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='gas',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='current_gas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='prev_gas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatch',
            name='time_out',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
