# Generated by Django 5.1.3 on 2024-12-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0008_remove_dispatch_date_and_time_remove_dispatch_gas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='short_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='boundary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='target_boundary',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
