# Generated by Django 5.1.3 on 2024-12-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0009_dispatch_short_amount_alter_dispatch_boundary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='boundary',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='current_gas',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='gas_deficit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='is_short',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='short_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
