# Generated by Django 5.1.3 on 2024-12-01 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0010_alter_dispatch_boundary_alter_dispatch_current_gas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='time_in',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='time_out',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
