# Generated by Django 5.1.3 on 2024-12-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0011_alter_dispatch_time_in_alter_dispatch_time_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='time_out',
        ),
    ]
