# Generated by Django 5.1.3 on 2024-12-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0013_dispatch_time_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='time_in',
        ),
    ]
