# Generated by Django 5.1.3 on 2024-12-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0014_remove_dispatch_time_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='time_in',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
