# Generated by Django 5.1.3 on 2024-12-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0015_dispatch_time_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='time_out',
        ),
    ]
