# Generated by Django 5.1.3 on 2024-12-01 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0016_remove_dispatch_time_in_remove_dispatch_time_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='time_in',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='time_out',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
