# Generated by Django 5.1.3 on 2024-12-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0017_dispatch_time_in_dispatch_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='image',
            field=models.URLField(default='None', null=True),
        ),
    ]
