# Generated by Django 5.1.3 on 2024-12-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverMonitoring', '0018_alter_dispatch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='image',
            field=models.URLField(blank=True, default='None', null=True),
        ),
    ]
